services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - examplenetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 5

networks:
  examplenetwork:

volumes:
  postgres-data:
    driver: local

